repos:
  - repo: local
    hooks:
      - id: swiftformat
        name: SwiftFormat
        entry: bin/mise exec -- swiftformat
        language: system
        types: [swift]
        args: []

      - id: swiftlint
        name: SwiftLint
        entry: bin/mise exec -- swiftlint lint --strict
        language: system
        types: [swift]

      - id: mdformat
        name: Markdown Format
        entry: bin/mise exec -- mdformat
        language: system
        types: [markdown]
        args: [--wrap, "120", --number]
        exclude: ^\.github/ISSUE_TEMPLATE/

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, chore, ci, revert]
