blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/alexey1312/ExFig/blob/main/.github/docs/index.md
    about: Check the documentation before opening an issue
  - name: Questions & Discussions
    url: https://github.com/alexey1312/ExFig/discussions
    about: Ask questions and discuss ideas
